wiki: Add Redmi Note 12 5G/Poco X5 5g (stone)
halcyonproject/wiki pull request #28
Opened 2024-08-27 06:26 UTC by Nomishaw21

2024-08-29 17:08 UTC, Nomishaw21 reviewed
Yes

2024-08-30 14:39 UTC, neroices requested changes

2024-08-30 14:39 UTC, neroices commented on docs/official_devices/list.md
> +- [POCO x5 5g / Redmi note 12 5g (stone)](/devices/stone)
Why are you adding the device to discontinued support?
Also, please use proper naming (capitalization, etc.)

Here's my suggestion:
```
- [POCO X5 5G / Redmi Note 12 5G(stone)](/devices/stone)
```

2024-08-30 14:39 UTC, neroices commented on docs/official_devices/xiaomi/stone.md
It seems you're using GNU Nano as your editor

2024-08-30 14:39 UTC, neroices commented on docs/official_devices/xiaomi/stone.md
> +title: "Redmi Note 12 5G / POCO X5 5G (stone)*"
```
title: "POCO X5 5G / Redmi Note 12 5G(stone)"
```

2024-08-30 14:39 UTC, neroices commented on docs/official_devices/xiaomi/stone.md
> +1. Enter fastboot mode by using a key combination `Power + Vol Do>
*Vol Down.

2024-08-30 14:39 UTC, neroices commented on docs/official_devices/xiaomi/stone.md
> +4. Flash the boot image onto your device using `fastboot flash bo>
```
`fastboot flash boot recovery.img`.
```

2024-08-30 14:39 UTC, neroices commented on docs/official_devices/xiaomi/stone.md
> +If you encounter any issues during or after the installation, fee>
*feel free to ask to our chat group for solutions to common problems.

2024-08-30 15:15 UTC, merged